// yss_orbit\generate_pages_1.js
const fs = require('fs');
const path = require('path');

const pages = [
  {
    path: 'frontend/src/modules/retailBilling/pages/CreditNotePage.tsx',
    content: `import React, { useState } from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function CreditNotePage() {\n  const [notes, setNotes] = useState([]);\n  \n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Credit Notes</h1>\n        <Button variant="primary">Create Credit Note</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-4">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead>\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Note ID</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Customer</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            {notes.length === 0 ? (\n              <tr><td colSpan={5} className="px-6 py-4 text-center text-sm text-gray-500">No credit notes found</td></tr>\n            ) : null}\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/retailBilling/pages/CustomerStatementPage.tsx',
    content: `import React, { useState } from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function CustomerStatementPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Customer Statements</h1>\n        <Button variant="outline">Export PDF</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <div className="mb-4">\n          <label className="block text-sm font-medium text-gray-700">Select Customer</label>\n          <select className="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-primary focus:border-primary sm:text-sm rounded-md">\n            <option>Select a customer...</option>\n          </select>\n        </div>\n        <div className="mt-8 border-t border-gray-200 pt-6">\n          <h2 className="text-lg font-medium text-gray-900">Statement Details</h2>\n          <p className="mt-2 text-sm text-gray-500">Please select a customer to view their statement.</p>\n        </div>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/retailBilling/pages/InvoicePage.tsx',
    content: `import React, { useState } from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InvoicePage() {\n  const [invoices, setInvoices] = useState([]);\n  \n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Invoices</h1>\n        <Button variant="primary">Generate Invoice</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Invoice #</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Client</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Total</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Due Date</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr><td colSpan={5} className="px-6 py-4 text-center text-sm text-gray-500">No invoices generated yet</td></tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/retailBilling/pages/PaymentPage.tsx',
    content: `import React, { useState } from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function PaymentPage() {\n  const [payments, setPayments] = useState([]);\n  \n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Payments</h1>\n        <Button variant="primary">Record Payment</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Payment ID</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Invoice #</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Method</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr><td colSpan={5} className="px-6 py-4 text-center text-sm text-gray-500">No payments recorded</td></tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/retailBilling/pages/retailBillingDetailPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function RetailBillingDetailPage() {\n  return (\n    <div className="p-6 max-w-4xl mx-auto">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Billing Details</h1>\n        <div className="space-x-3">\n          <Button variant="outline">Print</Button>\n          <Button variant="primary">Edit Details</Button>\n        </div>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <div className="grid grid-cols-2 gap-6">\n          <div>\n            <h3 className="text-sm font-medium text-gray-500">Billing ID</h3>\n            <p className="mt-1 text-sm text-gray-900">BIL-2023-0001</p>\n          </div>\n          <div>\n            <h3 className="text-sm font-medium text-gray-500">Customer</h3>\n            <p className="mt-1 text-sm text-gray-900">Acme Corp</p>\n          </div>\n          <div>\n            <h3 className="text-sm font-medium text-gray-500">Total Amount</h3>\n            <p className="mt-1 text-sm text-gray-900">$1,250.00</p>\n          </div>\n          <div>\n            <h3 className="text-sm font-medium text-gray-500">Status</h3>\n            <p className="mt-1 text-sm text-gray-900">\n              <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Paid</span>\n            </p>\n          </div>\n        </div>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/retailBilling/pages/retailBillingListPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function RetailBillingListPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Retail Billings</h1>\n        <Button variant="primary">New Billing</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <div className="p-4 border-b border-gray-200 bg-gray-50">\n          <input type="text" placeholder="Search billings..." className="w-full sm:w-64 px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-primary focus:border-primary" />\n        </div>\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Billing ID</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Customer Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-primary">BIL-2023-0001</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">John Doe</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Oct 24, 2023</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">$250.00</td>\n              <td className="px-6 py-4 whitespace-nowrap">\n                <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">Pending</span>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  }
];

pages.forEach(page => {
  const fullPath = path.join('c:/PROJECT/yss_orbit', page.path);
  fs.writeFileSync(fullPath, page.content, 'utf8');
  console.log('Wrote to ' + fullPath);
});
