// yss_orbit\generate_pages_3.js
const fs = require('fs');
const path = require('path');

const pages = [
  {
    path: 'frontend/src/modules/pharmacyBilling/pages/InsurancePage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InsurancePage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Insurance Claims</h1>\n        <Button variant="primary">New Claim</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6 text-center text-gray-500">\n        <p>No insurance claims have been submitted yet.</p>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/pharmacyBilling/pages/pharmacyBillingDetailPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function PharmacyBillingDetailPage() {\n  return (\n    <div className="p-6 max-w-4xl mx-auto">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Pharmacy Bill Details</h1>\n        <Button variant="outline">Print Receipt</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <div className="border-b border-gray-200 pb-4 mb-4 flex justify-between">\n          <div>\n            <h3 className="text-lg font-medium">Bill #PHB-001</h3>\n            <p className="text-sm text-gray-500">Date: Oct 24, 2023</p>\n          </div>\n          <div className="text-right">\n            <h3 className="text-lg font-medium">Patient: John Doe</h3>\n            <p className="text-sm text-gray-500">Dr. Smith</p>\n          </div>\n        </div>\n        <table className="min-w-full">\n          <thead>\n            <tr className="border-b border-gray-200">\n              <th className="py-2 text-left text-sm font-medium text-gray-500">Item</th>\n              <th className="py-2 text-right text-sm font-medium text-gray-500">Qty</th>\n              <th className="py-2 text-right text-sm font-medium text-gray-500">Price</th>\n              <th className="py-2 text-right text-sm font-medium text-gray-500">Total</th>\n            </tr>\n          </thead>\n          <tbody>\n            <tr className="border-b border-gray-100">\n              <td className="py-3 text-sm text-gray-900">Amoxicillin 500mg</td>\n              <td className="py-3 text-sm text-gray-900 text-right">20</td>\n              <td className="py-3 text-sm text-gray-900 text-right">$0.50</td>\n              <td className="py-3 text-sm text-gray-900 text-right">$10.00</td>\n            </tr>\n          </tbody>\n          <tfoot>\n            <tr>\n              <td colSpan={3} className="py-3 text-sm font-medium text-gray-900 text-right">Total Amount:</td>\n              <td className="py-3 text-sm font-bold text-gray-900 text-right">$10.00</td>\n            </tr>\n          </tfoot>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/pharmacyBilling/pages/pharmacyBillingListPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function PharmacyBillingListPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Pharmacy Bills</h1>\n        <Button variant="primary">Create Bill</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Bill ID</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Patient Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Amount</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-primary">PHB-001</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">John Doe</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Oct 24, 2023</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">$10.00</td>\n              <td className="px-6 py-4 whitespace-nowrap">\n                <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Paid</span>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/pharmacyBilling/pages/PrescriptionPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function PrescriptionPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Prescriptions</h1>\n        <Button variant="primary">Add Prescription</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <p className="text-sm text-gray-500 text-center">No active prescriptions found.</p>\n      </div>\n    </div>\n  );\n}`
  }
];

pages.forEach(page => {
  const fullPath = path.join('c:/PROJECT/yss_orbit', page.path);
  fs.writeFileSync(fullPath, page.content, 'utf8');
  console.log('Wrote to ' + fullPath);
});
