// yss_orbit\generate_pages_4.js
const fs = require('fs');
const path = require('path');

const pages = [
  {
    path: 'frontend/src/modules/inventory/pages/InventoryAdjustmentPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryAdjustmentPage() {\n  return (\n    <div className="p-6 max-w-2xl mx-auto">\n      <h1 className="text-2xl font-bold text-gray-900 mb-6">Inventory Adjustment</h1>\n      <form className="bg-white shadow rounded-lg p-6 space-y-6">\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Select Item</label>\n          <select className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm">\n            <option>Paracetamol 500mg</option>\n            <option>Amoxicillin 250mg</option>\n          </select>\n        </div>\n        <div className="grid grid-cols-2 gap-6">\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Adjustment Type</label>\n            <select className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm">\n              <option>Add Stock (Found)</option>\n              <option>Remove Stock (Damaged/Lost)</option>\n            </select>\n          </div>\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Quantity</label>\n            <input type="number" min="1" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n          </div>\n        </div>\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Reason</label>\n          <textarea rows={3} className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm"></textarea>\n        </div>\n        <div className="flex justify-end pt-4 border-t border-gray-200">\n          <Button variant="primary">Submit Adjustment</Button>\n        </div>\n      </form>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/inventory/pages/InventoryBatchPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryBatchPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Batch Management</h1>\n        <Button variant="primary">Register New Batch</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Batch Number</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Expiry Date</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">BATCH-23A-01</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Paracetamol 500mg</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">2025-12-31</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">1000</td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/inventory/pages/inventoryDetailPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryDetailPage() {\n  return (\n    <div className="p-6 max-w-4xl mx-auto">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Item Details</h1>\n        <Button variant="outline">Edit Item</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <h2 className="text-xl font-bold text-gray-900">Paracetamol 500mg</h2>\n        <p className="text-sm text-gray-500 mb-6">Category: Medicine • SKU: MED-001</p>\n        \n        <div className="grid grid-cols-3 gap-6 mb-8">\n          <div className="bg-gray-50 p-4 rounded-lg">\n            <h4 className="text-sm font-medium text-gray-500">Current Stock</h4>\n            <p className="text-2xl font-bold text-gray-900">1,500</p>\n          </div>\n          <div className="bg-gray-50 p-4 rounded-lg">\n            <h4 className="text-sm font-medium text-gray-500">Reorder Level</h4>\n            <p className="text-2xl font-bold text-gray-900">200</p>\n          </div>\n          <div className="bg-gray-50 p-4 rounded-lg">\n            <h4 className="text-sm font-medium text-gray-500">Unit Price</h4>\n            <p className="text-2xl font-bold text-gray-900">$0.50</p>\n          </div>\n        </div>\n        \n        <h3 className="text-lg font-medium text-gray-900 mb-4">Recent Transactions</h3>\n        <p className="text-sm text-gray-500">No recent transactions to display.</p>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/inventory/pages/inventoryListPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryListPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Inventory Items</h1>\n        <Button variant="primary">Add New Item</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">SKU</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Category</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Stock</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-primary">MED-001</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">Paracetamol 500mg</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Medicine</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">1,500</td>\n              <td className="px-6 py-4 whitespace-nowrap">\n                <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">In Stock</span>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/inventory/pages/InventoryReorderPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryReorderPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Reorder Alerts</h1>\n        <Button variant="primary">Generate Purchase Order</Button>\n      </div>\n      <div className="bg-yellow-50 border-l-4 border-yellow-400 p-4 mb-6">\n        <div className="flex">\n          <div className="ml-3">\n            <p className="text-sm text-yellow-700">\n              There are currently 2 items below their reorder threshold.\n            </p>\n          </div>\n        </div>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Current Stock</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Reorder Level</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Action</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Bandages</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-red-600 font-bold">15</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">50</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">\n                <Button variant="outline" size="sm">Order Now</Button>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/inventory/pages/InventoryStockPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function InventoryStockPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Current Stock Levels</h1>\n        <Button variant="outline">Export Report</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <div className="h-64 flex items-center justify-center bg-gray-50 border border-dashed border-gray-300 rounded-lg">\n          <p className="text-gray-500">Stock visualization chart will appear here</p>\n        </div>\n        <div className="mt-8">\n          <h3 className="text-lg font-medium text-gray-900 mb-4">Summary</h3>\n          <div className="grid grid-cols-4 gap-4">\n            <div className="p-4 bg-blue-50 rounded-lg border border-blue-100">\n              <p className="text-sm text-blue-600 font-medium">Total Value</p>\n              <p className="text-2xl font-bold text-blue-900">$45,230</p>\n            </div>\n            <div className="p-4 bg-green-50 rounded-lg border border-green-100">\n              <p className="text-sm text-green-600 font-medium">Items in Stock</p>\n              <p className="text-2xl font-bold text-green-900">1,204</p>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  );\n}`
  }
];

pages.forEach(page => {
  const fullPath = path.join('c:/PROJECT/yss_orbit', page.path);
  fs.writeFileSync(fullPath, page.content, 'utf8');
  console.log('Wrote to ' + fullPath);
});
