// yss_orbit\generate_pages_2.js
const fs = require('fs');
const path = require('path');

const pages = [
  {
    path: 'frontend/src/modules/hrmsCore/pages/DepartmentPage.tsx',
    content: `import React, { useState } from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function DepartmentPage() {\n  const [departments, setDepartments] = useState([\n    { id: 1, name: 'Engineering', head: 'Alice Smith', count: 45 },\n    { id: 2, name: 'Sales', head: 'Bob Johnson', count: 12 },\n  ]);\n\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Departments</h1>\n        <Button variant="primary">Add Department</Button>\n      </div>\n      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">\n        {departments.map(dept => (\n          <div key={dept.id} className="bg-white shadow rounded-lg p-6">\n            <h3 className="text-lg font-medium text-gray-900">{dept.name}</h3>\n            <p className="text-sm text-gray-500 mt-2">Head: {dept.head}</p>\n            <p className="text-sm text-gray-500">Employees: {dept.count}</p>\n            <div className="mt-4 flex space-x-3">\n              <Button variant="outline" size="sm">Edit</Button>\n              <Button variant="outline" size="sm">View Staff</Button>\n            </div>\n          </div>\n        ))}\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/DesignationPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function DesignationPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Designations & Roles</h1>\n        <Button variant="primary">Add Designation</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Department</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Level</th>\n              <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">Software Engineer</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Engineering</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">L3</td>\n              <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">\n                <a href="#" className="text-primary hover:text-primary-hover">Edit</a>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/EmployeeCreatePage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function EmployeeCreatePage() {\n  return (\n    <div className="p-6 max-w-2xl mx-auto">\n      <h1 className="text-2xl font-bold text-gray-900 mb-6">Onboard New Employee</h1>\n      <form className="bg-white shadow rounded-lg p-6 space-y-6">\n        <div className="grid grid-cols-2 gap-6">\n          <div>\n            <label className="block text-sm font-medium text-gray-700">First Name</label>\n            <input type="text" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n          </div>\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Last Name</label>\n            <input type="text" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n          </div>\n        </div>\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Email Address</label>\n          <input type="email" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n        </div>\n        <div className="grid grid-cols-2 gap-6">\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Department</label>\n            <select className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm">\n              <option>Engineering</option>\n              <option>Sales</option>\n            </select>\n          </div>\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Role/Designation</label>\n            <select className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm">\n              <option>Software Engineer</option>\n              <option>Manager</option>\n            </select>\n          </div>\n        </div>\n        <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">\n          <Button variant="ghost">Cancel</Button>\n          <Button variant="primary">Create Employee</Button>\n        </div>\n      </form>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/EmployeeEditPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function EmployeeEditPage() {\n  return (\n    <div className="p-6 max-w-2xl mx-auto">\n      <h1 className="text-2xl font-bold text-gray-900 mb-6">Edit Employee Profile</h1>\n      <form className="bg-white shadow rounded-lg p-6 space-y-6">\n        <div className="grid grid-cols-2 gap-6">\n          <div>\n            <label className="block text-sm font-medium text-gray-700">First Name</label>\n            <input type="text" defaultValue="John" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n          </div>\n          <div>\n            <label className="block text-sm font-medium text-gray-700">Last Name</label>\n            <input type="text" defaultValue="Doe" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n          </div>\n        </div>\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Email Address</label>\n          <input type="email" defaultValue="john.doe@example.com" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n        </div>\n        <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">\n          <Button variant="ghost">Cancel</Button>\n          <Button variant="primary">Save Changes</Button>\n        </div>\n      </form>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/EmployeeTerminatePage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function EmployeeTerminatePage() {\n  return (\n    <div className="p-6 max-w-lg mx-auto">\n      <h1 className="text-2xl font-bold text-gray-900 mb-6">Terminate Employee</h1>\n      <div className="bg-red-50 p-4 rounded-md mb-6 border border-red-200">\n        <h3 className="text-sm font-medium text-red-800">Warning</h3>\n        <div className="mt-2 text-sm text-red-700">\n          <p>This action will revoke the employee's access immediately and mark their profile as inactive.</p>\n        </div>\n      </div>\n      <form className="bg-white shadow rounded-lg p-6 space-y-6">\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Termination Date</label>\n          <input type="date" className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm" />\n        </div>\n        <div>\n          <label className="block text-sm font-medium text-gray-700">Reason for Termination</label>\n          <textarea rows={4} className="mt-1 block w-full border-gray-300 rounded-md shadow-sm focus:ring-primary focus:border-primary sm:text-sm"></textarea>\n        </div>\n        <div className="flex justify-end space-x-3 pt-4 border-t border-gray-200">\n          <Button variant="ghost">Cancel</Button>\n          <Button variant="danger">Confirm Termination</Button>\n        </div>\n      </form>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/hrmsCoreDetailPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function HrmsCoreDetailPage() {\n  return (\n    <div className="p-6 max-w-5xl mx-auto">\n      <div className="flex items-center justify-between mb-6">\n        <div className="flex items-center space-x-4">\n          <div className="h-16 w-16 rounded-full bg-gray-200 flex items-center justify-center text-xl font-bold text-gray-600">JD</div>\n          <div>\n            <h1 className="text-2xl font-bold text-gray-900">John Doe</h1>\n            <p className="text-sm text-gray-500">Senior Software Engineer • Engineering Department</p>\n          </div>\n        </div>\n        <div className="space-x-3">\n          <Button variant="outline">Edit Profile</Button>\n        </div>\n      </div>\n      <div className="bg-white shadow rounded-lg p-6">\n        <h3 className="text-lg font-medium text-gray-900 mb-4">Personal Information</h3>\n        <dl className="grid grid-cols-1 gap-x-4 gap-y-8 sm:grid-cols-2">\n          <div className="sm:col-span-1">\n            <dt className="text-sm font-medium text-gray-500">Email address</dt>\n            <dd className="mt-1 text-sm text-gray-900">john.doe@example.com</dd>\n          </div>\n          <div className="sm:col-span-1">\n            <dt className="text-sm font-medium text-gray-500">Phone number</dt>\n            <dd className="mt-1 text-sm text-gray-900">+1 555-0123</dd>\n          </div>\n          <div className="sm:col-span-1">\n            <dt className="text-sm font-medium text-gray-500">Date of Joining</dt>\n            <dd className="mt-1 text-sm text-gray-900">March 12, 2020</dd>\n          </div>\n          <div className="sm:col-span-1">\n            <dt className="text-sm font-medium text-gray-500">Status</dt>\n            <dd className="mt-1 text-sm text-gray-900">\n              <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Active</span>\n            </dd>\n          </div>\n        </dl>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/hrmsCoreListPage.tsx',
    content: `import React from 'react';\nimport { Button } from '../../../shared/components/Button';\n\nexport default function HrmsCoreListPage() {\n  return (\n    <div className="p-6">\n      <div className="flex justify-between items-center mb-6">\n        <h1 className="text-2xl font-bold text-gray-900">Employees</h1>\n        <Button variant="primary">Add Employee</Button>\n      </div>\n      <div className="bg-white shadow rounded-lg overflow-hidden">\n        <div className="p-4 border-b border-gray-200 flex justify-between">\n          <input type="text" placeholder="Search employees..." className="w-full sm:w-64 px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-primary focus:border-primary" />\n        </div>\n        <table className="min-w-full divide-y divide-gray-200">\n          <thead className="bg-gray-50">\n            <tr>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Name</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Title</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Department</th>\n              <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>\n            </tr>\n          </thead>\n          <tbody className="bg-white divide-y divide-gray-200">\n            <tr>\n              <td className="px-6 py-4 whitespace-nowrap">\n                <div className="flex items-center">\n                  <div className="flex-shrink-0 h-10 w-10 rounded-full bg-gray-200 flex items-center justify-center text-sm font-medium text-gray-600">JD</div>\n                  <div className="ml-4">\n                    <div className="text-sm font-medium text-gray-900">John Doe</div>\n                    <div className="text-sm text-gray-500">john.doe@example.com</div>\n                  </div>\n                </div>\n              </td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Software Engineer</td>\n              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">Engineering</td>\n              <td className="px-6 py-4 whitespace-nowrap">\n                <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">Active</span>\n              </td>\n            </tr>\n          </tbody>\n        </table>\n      </div>\n    </div>\n  );\n}`
  },
  {
    path: 'frontend/src/modules/hrmsCore/pages/OrgChartPage.tsx',
    content: `import React from 'react';\n\nexport default function OrgChartPage() {\n  return (\n    <div className="p-6">\n      <h1 className="text-2xl font-bold text-gray-900 mb-6">Organization Chart</h1>\n      <div className="bg-white shadow rounded-lg p-12 flex items-center justify-center min-h-[400px]">\n        <div className="text-center">\n          <div className="inline-block p-4 bg-gray-50 rounded-lg border border-gray-200 mb-8">\n            <h3 className="font-medium text-gray-900">CEO</h3>\n            <p className="text-sm text-gray-500">Sarah Connor</p>\n          </div>\n          <div className="flex space-x-12">\n            <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">\n              <h3 className="font-medium text-gray-900">CTO</h3>\n              <p className="text-sm text-gray-500">John Smith</p>\n            </div>\n            <div className="p-4 bg-gray-50 rounded-lg border border-gray-200">\n              <h3 className="font-medium text-gray-900">CFO</h3>\n              <p className="text-sm text-gray-500">Jane Doe</p>\n            </div>\n          </div>\n        </div>\n      </div>\n    </div>\n  );\n}`
  }
];

pages.forEach(page => {
  const fullPath = path.join('c:/PROJECT/yss_orbit', page.path);
  fs.writeFileSync(fullPath, page.content, 'utf8');
  console.log('Wrote to ' + fullPath);
});
