# Generated by Django 4.2.13 on 2026-07-05 07:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The Fully Qualified Domain Name (FQDN)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the primary domain for the tenant?",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Has the domain ownership been verified via DNS?",
                    ),
                ),
                (
                    "ssl_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Is SSL provisioning active for this domain?",
                    ),
                ),
                (
                    "ssl_status",
                    models.CharField(
                        blank=True,
                        help_text="Status of the SSL certificate issuance",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain",
                "verbose_name_plural": "Domains",
                "db_table": "domain_domains",
            },
        ),
        migrations.CreateModel(
            name="PlanModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_included", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plan_modules",
            },
        ),
        migrations.CreateModel(
            name="PlatformModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. 'inventory', 'hrms', 'pos'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CORE", "Core (Always included)"),
                            ("BUSINESS", "Business Operations"),
                            ("HRMS", "Human Resources"),
                            ("FINANCE", "Finance"),
                            ("ANALYTICS", "Analytics & Reporting"),
                            ("INTEGRATIONS", "Integrations"),
                        ],
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_free", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "platform_modules",
                "ordering": ["sort_order", "name"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SettingsTemplateModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "SettingsTemplateModel",
                "verbose_name_plural": "SettingsTemplateModels",
                "db_table": "tenant_settings_settings_template_model",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "price_monthly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "price_yearly",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("max_users", models.PositiveIntegerField(default=5)),
                ("max_business_units", models.PositiveIntegerField(default=1)),
                ("max_products", models.PositiveIntegerField(default=100)),
                ("max_api_calls_per_day", models.PositiveIntegerField(default=1000)),
                ("max_storage_gb", models.PositiveIntegerField(default=1)),
                ("is_featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "modules",
                    models.ManyToManyField(
                        blank=True,
                        through="tenancy.PlanModule",
                        to="tenancy.platformmodule",
                    ),
                ),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["sort_order", "price_monthly"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("STRING", "String"),
                            ("INTEGER", "Integer"),
                            ("BOOLEAN", "Boolean"),
                            ("JSON", "JSON Object"),
                        ],
                        default="STRING",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "tenant_settings",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("business_unit_id", "key")},
            },
        ),
        migrations.AddField(
            model_name="planmodule",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tenancy.platformmodule"
            ),
        ),
        migrations.AddField(
            model_name="planmodule",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tenancy.subscriptionplan",
            ),
        ),
        migrations.CreateModel(
            name="TenantModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("module_code", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "tenant_modules",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("business_unit_id", "module_code")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="planmodule",
            unique_together={("plan", "module")},
        ),
        migrations.CreateModel(
            name="DomainModuleMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "module_name",
                    models.CharField(
                        help_text="The internal module identifier (e.g., 'pos', 'hrms')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_maps",
                        to="tenancy.domain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Domain Module Map",
                "verbose_name_plural": "Domain Module Maps",
                "db_table": "domain_module_maps",
                "unique_together": {("domain", "module_name")},
            },
        ),
        migrations.CreateModel(
            name="BusinessUnitSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("business_unit_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Trial"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="TRIALING",
                        max_length=15,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[("MONTHLY", "Monthly"), ("YEARLY", "Yearly")],
                        default="MONTHLY",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "razorpay_subscription_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("razorpay_customer_id", models.CharField(blank=True, max_length=100)),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tenancy.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "business_unit_subscriptions",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["business_unit_id", "status"],
                        name="business_un_busines_4ac8ba_idx",
                    )
                ],
            },
        ),
    ]
