# Generated by Django 4.2.13 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunitsubscription",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="businessunitsubscription",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="businessunitsubscription",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domain",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domain",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domain",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domainmodulemap",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domainmodulemap",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="domainmodulemap",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="platformmodule",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="platformmodule",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="platformmodule",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="settingstemplatemodel",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="settingstemplatemodel",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="settingstemplatemodel",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantmodule",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantmodule",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantmodule",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tenantsetting",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
