# Generated by Django 4.2.13 on 2026-07-05 07:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIConsumerKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 10 chars of the key for identification",
                        max_length=10,
                    ),
                ),
                ("hashed_key", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="List of permission codes this key is authorized for.",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        help_text="The user this API key acts on behalf of."
                    ),
                ),
            ],
            options={
                "db_table": "api_consumer_keys",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APIKeyAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("api_key_id", models.UUIDField(db_index=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_key_audit_logs",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="APIKeyScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 'read:users'", max_length=100, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "api_key_scopes",
                "ordering": ["code"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("job_type", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("business_unit_id", models.UUIDField(db_index=True)),
                (
                    "triggered_by_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("progress_message", models.CharField(blank=True, max_length=500)),
                ("input_data", models.JSONField(default=dict)),
                ("result_data", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, null=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "background_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BrandConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "branding_mode",
                    models.CharField(
                        choices=[
                            ("platform", "Platform"),
                            ("co_brand", "Co-Brand"),
                            ("white_label", "White Label"),
                        ],
                        default="platform",
                        max_length=20,
                    ),
                ),
                ("logo_url", models.URLField(blank=True, max_length=1000, null=True)),
                (
                    "favicon_url",
                    models.URLField(blank=True, max_length=1000, null=True),
                ),
                ("primary_color", models.CharField(blank=True, max_length=7)),
                ("secondary_color", models.CharField(blank=True, max_length=7)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "domain_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "ssl_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("provisioning", "Provisioning"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "brand_configurations",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BreakGlassLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_tenant_id",
                    models.IntegerField(help_text="The Organization ID they accessed"),
                ),
                (
                    "reason",
                    models.TextField(help_text="Mandatory incident reason/ticket URL"),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                ("duration_minutes", models.IntegerField(default=60)),
            ],
            options={
                "db_table": "platform_admin_break_glass_logs",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.CreateModel(
            name="EventDeadLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_event_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("business_unit_id", models.UUIDField(db_index=True)),
                ("correlation_id", models.CharField(max_length=36)),
                ("payload", models.JSONField()),
                ("failure_reason", models.TextField()),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("resolved", models.BooleanField(db_index=True, default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_id", models.UUIDField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "event_dead_letter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventOutbox",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("event_version", models.CharField(default="1.0", max_length=10)),
                ("aggregate_type", models.CharField(max_length=100)),
                (
                    "aggregate_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("business_unit_id", models.UUIDField(db_index=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.CharField(db_index=True, max_length=36)),
                ("causation_id", models.UUIDField(blank=True, null=True)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("DEAD", "Dead (Max Retries Exceeded)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
                ("max_retries", models.PositiveSmallIntegerField(default=5)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_error", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "event_outbox",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-notation feature code. e.g. 'payroll.bulk_run'. Must be stable — used as cache key and in code.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable feature name for admin display.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What this feature enables and any caveats.",
                    ),
                ),
                (
                    "is_enabled_globally",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If True, all organizations have this feature regardless of other rules.",
                    ),
                ),
                (
                    "rollout_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percentage (0-100) of organizations to include via hash-based rollout. 0 = no rollout, 100 = all organizations.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "allowed_organizations",
                    models.JSONField(
                        default=list,
                        help_text="List of organization UUID strings explicitly allowed to use this feature.",
                    ),
                ),
                (
                    "allowed_plans",
                    models.JSONField(
                        default=list,
                        help_text="List of subscription plan codes (str) that have this feature enabled.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Master switch — if False the flag evaluates to False for everyone.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "feature_flags",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FileUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                (
                    "stored_key",
                    models.CharField(
                        help_text="S3 object key or storage path", max_length=1000
                    ),
                ),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("S3", "Amazon S3"),
                            ("GCS", "Google Cloud Storage"),
                            ("MINIO", "MinIO (self-hosted)"),
                            ("LOCAL", "Local filesystem (dev only)"),
                        ],
                        default="S3",
                        max_length=10,
                    ),
                ),
                ("content_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.PositiveBigIntegerField()),
                (
                    "file_hash_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("EMPLOYEE_DOCUMENT", "Employee Document"),
                            ("INVOICE", "Invoice"),
                            ("PURCHASE_ORDER", "Purchase Order"),
                            ("PRODUCT_IMAGE", "Product Image"),
                            ("BRANDING", "Branding Asset"),
                            ("PAYSLIP", "Payslip"),
                            ("REPORT", "Report Export"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("uploaded_by_id", models.UUIDField(db_index=True)),
                ("linked_resource_type", models.CharField(blank=True, max_length=100)),
                (
                    "linked_resource_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Scan"),
                            ("CLEAN", "Clean"),
                            ("INFECTED", "Infected"),
                            ("FAILED", "Scan Failed"),
                            ("SKIPPED", "Scan Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("is_public", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "file_uploads",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("slack", "Slack"),
                            ("stripe", "Stripe"),
                            ("github", "GitHub"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("credentials", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "integrations",
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=60)),
                ("recipient_user_id", models.UUIDField(db_index=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("IN_APP", "In-App"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                            ("PUSH", "Push"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("correlation_id", models.UUIDField(blank=True, null=True)),
                ("retry_count", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "notifications_log",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=60)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("in_app_enabled", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notifications_preferences",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LEAVE_APPLIED", "Leave Applied (to Manager)"),
                            ("LEAVE_APPROVED", "Leave Approved (to Employee)"),
                            ("LEAVE_REJECTED", "Leave Rejected (to Employee)"),
                            (
                                "ATTENDANCE_CORRECTION_SUBMITTED",
                                "Attendance Correction Submitted",
                            ),
                            (
                                "ATTENDANCE_CORRECTION_APPROVED",
                                "Attendance Correction Approved",
                            ),
                            ("PAYROLL_PROCESSED", "Payroll Processed (to HR/Finance)"),
                            ("PAYSLIP_AVAILABLE", "Payslip Available (to Employee)"),
                            ("DOC_EXPIRY_30_DAYS", "Document Expiring in 30 Days"),
                            ("DOC_EXPIRY_7_DAYS", "Document Expiring in 7 Days"),
                            ("DOC_EXPIRED", "Document Expired"),
                            ("TRANSFER_APPROVED", "Transfer Approved"),
                            ("PROMOTION_APPROVED", "Promotion Approved"),
                            ("EXIT_APPROVED", "Exit Approved"),
                            ("TRAINING_NOMINATED", "Training Nomination (to Employee)"),
                            ("TRAINING_COMPLETED", "Training Completed"),
                            ("APPRAISAL_LAUNCHED", "Appraisal Cycle Launched"),
                            ("APPRAISAL_SELF_REVIEW_DUE", "Self Review Due Reminder"),
                            ("ONBOARDING_TASK_DUE", "Onboarding Task Due"),
                            ("ONBOARDING_COMPLETED", "Onboarding Completed"),
                            ("IT_DECLARATION_DUE", "IT Declaration Deadline Reminder"),
                            ("IT_PROOF_REJECTED", "Investment Proof Rejected"),
                        ],
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("subject_template", models.CharField(max_length=500)),
                ("body_template", models.TextField()),
                ("sms_template", models.CharField(blank=True, max_length=160)),
                ("push_template", models.CharField(blank=True, max_length=255)),
                ("channels", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notifications_templates",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OutboxDeadLetter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_message_id", models.UUIDField(db_index=True)),
                ("message_type", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("error_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_dead_letter",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_type", models.CharField(db_index=True, max_length=100)),
                (
                    "destination",
                    models.CharField(
                        help_text="Where this message is headed (e.g., webhook url, queue name)",
                        max_length=255,
                    ),
                ),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "outbox_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_super_admin", models.BooleanField(default=False)),
                ("security_clearance_level", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "platform_admin_profiles",
            },
        ),
        migrations.CreateModel(
            name="Saga",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("saga_type", models.CharField(db_index=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("COMPENSATING", "Compensating"),
                            ("COMPENSATED", "Compensated"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Initial data required to execute the saga",
                    ),
                ),
                (
                    "correlation_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "business_unit_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orchestration_saga",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ThemeModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "ThemeModel",
                "verbose_name_plural": "ThemeModels",
                "db_table": "branding_theme_model",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("WAITING", "Waiting on Customer"),
                            ("RESOLVED", "Resolved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.UUIDField(
                        blank=True, help_text="ID of the assigned agent user", null=True
                    ),
                ),
                (
                    "customer_id",
                    models.UUIDField(
                        help_text="ID of the customer who raised the ticket"
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active_category", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "Ticket Categories",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "secret",
                    models.CharField(
                        help_text="HMAC-SHA256 signing secret. Never expose in API responses.",
                        max_length=256,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended (too many failures)"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "subscribed_events",
                    models.JSONField(
                        default=list,
                        help_text="List of event type strings this endpoint subscribes to. e.g. ['billing.invoice.created']",
                    ),
                ),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=10)),
                ("max_retries", models.PositiveSmallIntegerField(default=3)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "webhook_endpoints",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["business_unit_id", "status"],
                        name="webhook_end_busines_ade788_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                (
                    "event_id",
                    models.UUIDField(
                        db_index=True, help_text="ID of the source event."
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="The JSON payload sent to the endpoint."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_FLIGHT", "In Flight"),
                            ("SUCCESS", "Delivered Successfully"),
                            ("FAILED", "Delivery Failed"),
                            ("DEAD_LETTER", "Dead Letter (max retries exceeded)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "next_retry_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "response_status_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="platform.webhookendpoint",
                    ),
                ),
            ],
            options={
                "db_table": "webhook_deliveries",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("comment_text", models.TextField()),
                (
                    "author_id",
                    models.UUIDField(help_text="ID of the user who commented"),
                ),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="If true, only agents can see this comment",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="platform.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("file_url", models.URLField(max_length=1024)),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField(help_text="Size in bytes")),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attachments",
                        to="platform.ticketcomment",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="platform.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tickets",
                to="platform.ticketcategory",
            ),
        ),
        migrations.CreateModel(
            name="SagaStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_name", models.CharField(max_length=100)),
                ("step_order", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("COMPENSATED", "Compensated"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "result_payload",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "saga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="platform.saga",
                    ),
                ),
            ],
            options={
                "db_table": "orchestration_saga_step",
                "ordering": ["saga", "step_order"],
            },
        ),
        migrations.CreateModel(
            name="ProcessedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.UUIDField(db_index=True)),
                ("event_type", models.CharField(max_length=100)),
                ("consumer", models.CharField(max_length=200)),
                (
                    "processed_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("business_unit_id", models.UUIDField(db_index=True)),
            ],
            options={
                "db_table": "processed_events",
                "ordering": ["-processed_at"],
                "indexes": [
                    models.Index(
                        fields=["event_id", "consumer"],
                        name="processed_e_event_i_9a88c3_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="processedevent",
            constraint=models.UniqueConstraint(
                fields=("event_id", "consumer"), name="unique_processed_event_consumer"
            ),
        ),
        migrations.AddField(
            model_name="platformadminprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="platform_admin_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="outboxmessage",
            index=models.Index(
                fields=["status", "created_at"], name="outbox_mess_status_73b4cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together={("business_unit_id", "user_id", "event_type")},
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["business_unit_id", "recipient_user_id", "status"],
                name="notificatio_busines_f77d91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["business_unit_id", "event_type"],
                name="notificatio_busines_29ed20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["business_unit_id", "category", "is_active"],
                name="file_upload_busines_0d5193_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["linked_resource_type", "linked_resource_id"],
                name="file_upload_linked__e4eec4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileupload",
            index=models.Index(
                fields=["uploaded_by_id", "created_at"],
                name="file_upload_uploade_bfd22c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="featureflag",
            index=models.Index(
                fields=["is_active", "is_enabled_globally"],
                name="feature_fla_is_acti_7ca830_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventoutbox",
            index=models.Index(
                fields=["status", "next_retry_at"], name="event_outbo_status_7ff5b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventoutbox",
            index=models.Index(
                fields=["business_unit_id", "event_type", "created_at"],
                name="event_outbo_busines_3cb9dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventoutbox",
            index=models.Index(
                fields=["aggregate_type", "aggregate_id"],
                name="event_outbo_aggrega_36deb8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventdeadletter",
            index=models.Index(
                fields=["resolved", "created_at"], name="event_dead__resolve_76320a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventdeadletter",
            index=models.Index(
                fields=["event_type", "resolved"], name="event_dead__event_t_267895_idx"
            ),
        ),
        migrations.AddField(
            model_name="breakglasslog",
            name="admin_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="break_glass_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="brandconfiguration",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_configurations",
                to="organization.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="brandconfiguration",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand_configurations",
                to="organization.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["business_unit_id", "status", "created_at"],
                name="background__busines_d720c0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["triggered_by_id", "created_at"],
                name="background__trigger_335c97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["expires_at", "status"], name="background__expires_af1ae8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apiconsumerkey",
            index=models.Index(
                fields=["business_unit_id", "is_active"],
                name="api_consume_busines_b8daa9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="apiconsumerkey",
            index=models.Index(
                fields=["key_prefix"], name="api_consume_key_pre_278f6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["business_unit_id", "status", "next_retry_at"],
                name="webhook_del_busines_4eeb4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["endpoint", "status"], name="webhook_del_endpoin_4ffb63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webhookdelivery",
            index=models.Index(
                fields=["event_type", "created_at"],
                name="webhook_del_event_t_dae0cf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sagastep",
            unique_together={("saga", "step_name")},
        ),
        migrations.AddConstraint(
            model_name="brandconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "business_unit"),
                name="unique_brand_config_per_org_and_bu",
            ),
        ),
    ]
