# Generated by Django 4.2.13 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiconsumerkey",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiconsumerkey",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apiconsumerkey",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyaudit",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyaudit",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyaudit",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyscope",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyscope",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="apikeyscope",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="brandconfiguration",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="brandconfiguration",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="brandconfiguration",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="fileupload",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="thememodel",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="thememodel",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="thememodel",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticket",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketattachment",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcategory",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
