# Generated by Django 4.2.13 on 2026-07-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("platform", "0002_apiconsumerkey_created_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brandconfiguration",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="brandconfiguration",
            name="favicon_url",
        ),
        migrations.RemoveField(
            model_name="brandconfiguration",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="brandconfiguration",
            name="secondary_color",
        ),
    ]
