# Generated by Django 4.2.13 on 2026-07-05 07:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeTaxDeclaration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("employee_id", models.UUIDField(db_index=True)),
                ("financial_year", models.CharField(db_index=True, max_length=9)),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("OLD_REGIME", "Old Regime"),
                            ("NEW_REGIME", "New Regime (Default FY2024-25)"),
                        ],
                        default="NEW_REGIME",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("VERIFIED", "Verified by HR"),
                            ("LOCKED", "Locked for Payroll"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                (
                    "section_80c",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "section_80d",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "section_80e",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "section_80g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "section_80tta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hra_exemption",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "lta_exemption",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_exemptions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_declared_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_exemptions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "estimated_annual_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "monthly_tds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("verified_by_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_tax_declarations",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmployeeVariablePay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("employee_id", models.UUIDField(db_index=True)),
                ("period_label", models.CharField(max_length=20)),
                (
                    "performance_rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "calculated_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("APPROVED", "Approved"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=15,
                    ),
                ),
                ("payment_month", models.DateField(blank=True, null=True)),
                ("approved_by_id", models.UUIDField(blank=True, null=True)),
                ("paid_payslip_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_employee_variable_pay",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="GratuityConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "eligibility_years",
                    models.DecimalField(decimal_places=1, default=5.0, max_digits=4),
                ),
                (
                    "rate_per_year",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                ("working_days_divisor", models.IntegerField(default=26)),
                (
                    "max_gratuity_amount",
                    models.DecimalField(
                        decimal_places=2, default=2000000.0, max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_gratuity_config",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvestmentProofSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "proof_type",
                    models.CharField(
                        choices=[
                            ("LIC", "LIC Premium"),
                            ("PPF", "PPF Receipt"),
                            ("ELSS", "ELSS Statement"),
                            ("NSC", "NSC Certificate"),
                            ("NPS", "NPS Contribution"),
                            ("EPF", "EPF Contribution"),
                            ("HOME_LOAN", "Home Loan Statement"),
                            ("TUITION", "Tuition Fee Receipt"),
                            ("HEALTH_INS", "Health Insurance Premium"),
                            ("DONATION", "Donation Receipt 80G"),
                            ("HRA_RENT", "Rent Receipts for HRA"),
                            ("LTA", "LTA Travel Bills"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "declared_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "submitted_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("file_asset_id", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUBMITTED", "Submitted"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("verified_by_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "payroll_investment_proof_submissions",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LabourWelfareFundConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("state_code", models.CharField(db_index=True, max_length=5)),
                (
                    "employee_contribution",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "employer_contribution",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("BIANNUAL", "Bi-Annual"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="BIANNUAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_lwf_config",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MinimumWageConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("state_code", models.CharField(db_index=True, max_length=5)),
                (
                    "worker_category",
                    models.CharField(
                        choices=[
                            ("UNSKILLED", "Unskilled"),
                            ("SEMI_SKILLED", "Semi-Skilled"),
                            ("SKILLED", "Skilled"),
                            ("HIGHLY_SKILLED", "Highly Skilled"),
                        ],
                        max_length=30,
                    ),
                ),
                ("daily_wage", models.DecimalField(decimal_places=2, max_digits=12)),
                ("monthly_wage", models.DecimalField(decimal_places=2, max_digits=12)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_minimum_wage_config",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("month", models.IntegerField(default=1)),
                ("year", models.IntegerField(default=2024)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total_net",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("total_employees", models.IntegerField(default=0)),
                ("run_by_id", models.UUIDField(blank=True, null=True)),
                ("approved_by_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by_id", models.UUIDField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("correlation_id", models.CharField(default=uuid.uuid4, max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "PayrollRun",
                "verbose_name_plural": "PayrollRuns",
                "db_table": "payroll_runs",
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("employee_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("employee_code", models.CharField(blank=True, max_length=50)),
                ("employee_name", models.CharField(blank=True, max_length=255)),
                ("salary_structure_id", models.UUIDField(blank=True, null=True)),
                ("month", models.IntegerField(default=1)),
                ("year", models.IntegerField(default=2024)),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("CHEQUE", "Cheque"),
                            ("CASH", "Cash"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=50,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "working_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "paid_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "lop_days",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "gross_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "employee_pf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "employer_pf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "employee_esi",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "employer_esi",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tds",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("earnings_breakdown", models.JSONField(blank=True, default=dict)),
                ("deductions_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("GENERATED", "Generated"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "payroll_payslip",
            },
        ),
        migrations.CreateModel(
            name="ProfessionalTaxSlab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "state_code",
                    models.CharField(
                        choices=[
                            ("KA", "Karnataka"),
                            ("MH", "Maharashtra"),
                            ("WB", "West Bengal"),
                            ("AP", "Andhra Pradesh"),
                            ("TS", "Telangana"),
                            ("TN", "Tamil Nadu"),
                            ("GJ", "Gujarat"),
                            ("MP", "Madhya Pradesh"),
                            ("OR", "Odisha"),
                            ("AS", "Assam"),
                            ("KL", "Kerala"),
                            ("MN", "Manipur"),
                            ("ME", "Meghalaya"),
                            ("MZ", "Mizoram"),
                            ("SK", "Sikkim"),
                            ("NA", "Not Applicable"),
                        ],
                        db_index=True,
                        max_length=5,
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                ("salary_from", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "salary_to",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "monthly_pt_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_professional_tax_slabs",
                "ordering": ["state_code", "salary_from"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RetentionBonus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("employee_id", models.UUIDField(db_index=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vesting_date", models.DateField()),
                ("service_condition_months", models.IntegerField()),
                ("grant_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("VESTED", "Vested"),
                            ("FORFEITED", "Forfeited"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("forfeited_at", models.DateTimeField(blank=True, null=True)),
                ("vested_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "payroll_retention_bonus",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("component_type", models.CharField(default="EARNING", max_length=50)),
                ("calculation_type", models.CharField(default="FLAT", max_length=50)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_taxable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SalaryComponent",
                "verbose_name_plural": "SalaryComponents",
                "db_table": "payroll_salary_component",
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SalaryStructure",
                "verbose_name_plural": "SalaryStructures",
                "db_table": "payroll_salary_structure",
            },
        ),
        migrations.CreateModel(
            name="StatutoryBonusConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "min_bonus_pct",
                    models.DecimalField(decimal_places=2, default=8.33, max_digits=5),
                ),
                (
                    "max_bonus_pct",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "salary_ceiling",
                    models.DecimalField(
                        decimal_places=2, default=21000.0, max_digits=12
                    ),
                ),
                (
                    "bonus_calculation_ceiling",
                    models.DecimalField(
                        decimal_places=2, default=7000.0, max_digits=12
                    ),
                ),
                ("financial_year", models.CharField(max_length=9)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_statutory_bonus_config",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TDSSlab",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("financial_year", models.CharField(max_length=20)),
                ("min_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "max_income",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "surcharge_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "cess_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TDS Slab",
                "verbose_name_plural": "TDS Slabs",
                "db_table": "payroll_tds_slabs",
            },
        ),
        migrations.CreateModel(
            name="VariablePayPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("QUARTERLY", "Quarterly"),
                            ("ANNUAL", "Annual"),
                            ("PROJECT", "Project-Based"),
                            ("AD_HOC", "Ad-Hoc"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "calculation_method",
                    models.CharField(
                        choices=[
                            ("FIXED_AMOUNT", "Fixed Amount"),
                            ("PCT_OF_CTC", "% of Annual CTC"),
                            ("PCT_OF_BASIC", "% of Basic Salary"),
                            ("PERFORMANCE_LINKED", "Performance Rating Linked"),
                        ],
                        max_length=25,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("performance_matrix", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "payroll_variable_pay_plans",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SalaryStructureComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payroll.salarycomponent",
                    ),
                ),
                (
                    "structure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="payroll.salarystructure",
                    ),
                ),
            ],
            options={
                "db_table": "payroll_salary_structure_components",
            },
        ),
        migrations.AddConstraint(
            model_name="salarystructure",
            constraint=models.UniqueConstraint(
                fields=("business_unit_id", "name"), name="unique_salary_structure_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="salarycomponent",
            constraint=models.UniqueConstraint(
                fields=("business_unit_id", "code"), name="unique_salary_component_code"
            ),
        ),
        migrations.AddIndex(
            model_name="retentionbonus",
            index=models.Index(
                fields=["business_unit_id", "employee_id", "status"],
                name="payroll_ret_busines_147e9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="retentionbonus",
            index=models.Index(
                fields=["business_unit_id", "vesting_date"],
                name="payroll_ret_busines_3def1b_idx",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="payroll_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="payroll.payrollrun",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.UniqueConstraint(
                fields=("business_unit_id", "month", "year"),
                name="unique_payroll_run_per_month",
            ),
        ),
        migrations.AddField(
            model_name="investmentproofsubmission",
            name="declaration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proofs",
                to="payroll.employeetaxdeclaration",
            ),
        ),
        migrations.AddField(
            model_name="employeevariablepay",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="awards",
                to="payroll.variablepayplan",
            ),
        ),
        migrations.AddIndex(
            model_name="employeetaxdeclaration",
            index=models.Index(
                fields=["business_unit_id", "financial_year", "status"],
                name="payroll_tax_busines_e85906_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeetaxdeclaration",
            unique_together={("business_unit_id", "employee_id", "financial_year")},
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["business_unit_id", "employee_id"], name="payslip_bu_emp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["business_unit_id", "year", "month"],
                name="payslip_bu_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["business_unit_id", "status"], name="payslip_bu_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payslip",
            index=models.Index(
                fields=["business_unit_id", "payroll_run_id"], name="payslip_bu_run_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeevariablepay",
            index=models.Index(
                fields=["business_unit_id", "employee_id", "status"],
                name="payroll_emp_busines_6de006_idx",
            ),
        ),
    ]
