# Generated by Django 4.2.13 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeetaxdeclaration",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetaxdeclaration",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetaxdeclaration",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeevariablepay",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeevariablepay",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeevariablepay",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gratuityconfig",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gratuityconfig",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="gratuityconfig",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="investmentproofsubmission",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="investmentproofsubmission",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="investmentproofsubmission",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="labourwelfarefundconfig",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="labourwelfarefundconfig",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="labourwelfarefundconfig",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="minimumwageconfig",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="minimumwageconfig",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="minimumwageconfig",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payrollrun",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payslip",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payslip",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payslip",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="professionaltaxslab",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="professionaltaxslab",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="professionaltaxslab",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="retentionbonus",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="retentionbonus",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="retentionbonus",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarycomponent",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructure",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructurecomponent",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructurecomponent",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salarystructurecomponent",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="statutorybonusconfig",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="statutorybonusconfig",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="statutorybonusconfig",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tdsslab",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tdsslab",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="tdsslab",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="variablepayplan",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="variablepayplan",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="variablepayplan",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
