# Generated by Django 4.2.13 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="asset",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="asset",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetassignment",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assetcategory",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendanceconfig",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendanceconfig",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendanceconfig",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancecorrectionrequest",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancepunch",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancepunch",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancepunch",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="costcenter",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="department",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="department",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="department",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="designation",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="designation",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="designation",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employee",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employee",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employee",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeecostallocation",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeecostallocation",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeecostallocation",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeedocument",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeevent",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeevent",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeevent",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeimportsession",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeimportsession",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeimportsession",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeonboarding",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeonboarding",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeeonboarding",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeepromotion",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeepromotion",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeepromotion",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetraining",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="employeetransfer",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="exitrequest",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="finalsettlement",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holiday",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holiday",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holiday",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holidaycalendar",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holidaycalendar",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="holidaycalendar",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="hranalyticssnapshot",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="hranalyticssnapshot",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="hranalyticssnapshot",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaveattachment",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaveattachment",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaveattachment",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavebalance",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicy",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicyassignment",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicyassignment",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavepolicyassignment",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequesthistory",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequesthistory",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverequesthistory",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverestrictionwindow",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverestrictionwindow",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leaverestrictionwindow",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="manpowerrequest",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="manpowerrequest",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="manpowerrequest",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtask",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtaskcompletion",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtaskcompletion",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtaskcompletion",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtemplate",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtemplate",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="onboardingtemplate",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="position",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="position",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="position",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="salaryrevision",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shift",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shift",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shift",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trainingcourse",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trainingcourse",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="trainingcourse",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
