# Generated by Django 4.2.13 on 2026-07-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appraisal", "0001_initial"),
        ("hrms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancereview",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_reviews",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="reviewer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_given",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="hrms.employee",
            ),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="cycle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appraisals",
                to="appraisal.reviewcycle",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appraisal",
            unique_together={("cycle", "employee_id")},
        ),
    ]
