# Generated by Django 4.2.13 on 2026-07-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appraisal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appraisal",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="appraisal",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="feedback",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="goal",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kpi",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kpi",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="kpi",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="performancereview",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
