# yss_orbit\backend\core\audit\audit_events.py
"""
Standardized audit event names.
"""
class AuditEvents:
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"
    USER_CREATED = "USER_CREATED"
    USER_UPDATED = "USER_UPDATED"
    USER_DELETED = "USER_DELETED"
    
    TENANT_CREATED = "TENANT_CREATED"
    TENANT_UPDATED = "TENANT_UPDATED"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
    
    PASSWORD_CHANGED = "PASSWORD_CHANGED"
    MFA_ENABLED = "MFA_ENABLED"
    MFA_DISABLED = "MFA_DISABLED"
    
    RESOURCE_ACCESSED = "RESOURCE_ACCESSED"
    RESOURCE_MODIFIED = "RESOURCE_MODIFIED"
    RESOURCE_DELETED = "RESOURCE_DELETED"
    
    PAYMENT_PROCESSED = "PAYMENT_PROCESSED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
