# Generated by Django 4.2.13 on 2026-07-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_roletemplate_created_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="created_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="restored_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="restored_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
