# yss_orbit/backend/apps/core/error_codes.py
"""
YSS Orbit — X02 Error Code Registry
ALL error codes as string constants mapped to canonical X02 Rulebook strings.
"""

# ─── Authentication (401 / 200) ─────────────────────────────────────────────
AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
TOKEN_EXPIRED = "TOKEN_EXPIRED"
TOKEN_INVALID = "TOKEN_INVALID"
TOKEN_TYPE_MISMATCH = "TOKEN_TYPE_MISMATCH"
SESSION_EXPIRED = "SESSION_EXPIRED"
ACCOUNT_LOCKED = "ACCOUNT_LOCKED"
ACCOUNT_INACTIVE = "ACCOUNT_INACTIVE"
MFA_REQUIRED = "MFA_REQUIRED"
MFA_INVALID = "MFA_INVALID"
EMAIL_VERIFICATION_REQUIRED = "EMAIL_VERIFICATION_REQUIRED"
MFA_OTP_SENT = "MFA_OTP_SENT"
EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED"
OTP_INVALID = "OTP_INVALID"
OTP_EXPIRED = "OTP_EXPIRED"
OTP_ALREADY_USED = "OTP_ALREADY_USED"
OTP_MAX_ATTEMPTS_EXCEEDED = "OTP_MAX_ATTEMPTS_EXCEEDED"
RESET_TOKEN_INVALID = "RESET_TOKEN_INVALID"
RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED"

# ─── Authorization (403) ────────────────────────────────────────────────────
PERMISSION_DENIED = "PERMISSION_DENIED"
BUSINESS_UNIT_ACCESS_DENIED = "BUSINESS_UNIT_ACCESS_DENIED"
CROSS_TENANT_ACCESS_DENIED = "CROSS_TENANT_ACCESS_DENIED"
GLOBAL_SCOPE_REQUIRED = "GLOBAL_SCOPE_REQUIRED"
MODULE_NOT_SUBSCRIBED = "MODULE_NOT_SUBSCRIBED"

# ─── Validation & Business Rules (400 / 422) ────────────────────────────────
VALIDATION_ERROR = "VALIDATION_ERROR"
MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
INVALID_FIELD_VALUE = "INVALID_FIELD_VALUE"
INVALID_UUID = "INVALID_UUID"
INVALID_PAGINATION = "INVALID_PAGINATION"
BUSINESS_RULE_VIOLATION = "BUSINESS_RULE_VIOLATION"
INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"

# ─── Resource & Conflicts (404 / 409) ───────────────────────────────────────
NOT_FOUND = "NOT_FOUND"
BUSINESS_UNIT_NOT_FOUND = "BUSINESS_UNIT_NOT_FOUND"
CONFLICT = "CONFLICT"
DUPLICATE_ENTRY = "DUPLICATE_ENTRY"

# ─── Rate Limiting & Quotas (429 / 402) ─────────────────────────────────────
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
UPLOAD_QUOTA_EXCEEDED = "UPLOAD_QUOTA_EXCEEDED"
PLAN_LIMIT_EXCEEDED = "PLAN_LIMIT_EXCEEDED"

# ─── Files (400) ────────────────────────────────────────────────────────────
FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
FILE_MISSING = "FILE_MISSING"
FILE_CORRUPTED = "FILE_CORRUPTED"

# ─── Server & Infrastructure (5xx) ──────────────────────────────────────────
INTERNAL_ERROR = "INTERNAL_ERROR"
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
GATEWAY_TIMEOUT = "GATEWAY_TIMEOUT"
