# Generated by Django 4.2.13 on 2026-07-05 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenancy", "__first__"),
        ("iam", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDomain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Retail, Pharmacy, HRMS",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. BDOM-RTL", max_length=20, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier",
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("restored_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Business Domain",
                "verbose_name_plural": "Business Domains",
                "db_table": "business_domains",
                "ordering": ["name"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                (
                    "headquarters_address_1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "headquarters_address_2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, default="Asia/Kolkata", max_length=64),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, default="INR", max_length=3),
                ),
                ("owner_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_domain",
                    models.ForeignKey(
                        help_text="The industry classification of the customer.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="organization.businessdomain",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organization_organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "theme_color",
                    models.CharField(
                        default="#6366F1", help_text="Primary hex color", max_length=7
                    ),
                ),
                ("favicon_url", models.URLField(blank=True, max_length=500, null=True)),
                ("require_mfa", models.BooleanField(default=False)),
                ("session_timeout_minutes", models.IntegerField(default=60)),
                ("allowed_ip_ranges", models.JSONField(blank=True, default=list)),
                ("enable_audit_log", models.BooleanField(default=True)),
                ("enable_api_access", models.BooleanField(default=False)),
                (
                    "max_users",
                    models.IntegerField(
                        blank=True, help_text="Null = unlimited", null=True
                    ),
                ),
                ("notify_on_login", models.BooleanField(default=False)),
                ("notify_on_data_export", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Settings",
                "verbose_name_plural": "Organization Settings",
                "db_table": "organization_settings",
            },
        ),
        migrations.CreateModel(
            name="BusinessUnitModule",
            fields=[
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trial", "Trial"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "plan_limit",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom plan overrides for this specific module/tenant.",
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_modules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_business_units",
                        to="tenancy.platformmodule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Unit Module",
                "verbose_name_plural": "Business Unit Modules",
                "db_table": "business_unit_module",
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "code",
                    models.CharField(
                        help_text="2-20 uppercase alphanumeric chars. Validated by serializer.",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "address_line1",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "address_line2",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("country", models.CharField(default="IN", max_length=2)),
                ("pincode", models.CharField(blank=True, default="", max_length=10)),
                (
                    "registration_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("gst_number", models.CharField(blank=True, default="", max_length=20)),
                ("pan_number", models.CharField(blank=True, default="", max_length=20)),
                ("timezone", models.CharField(blank=True, default="", max_length=64)),
                (
                    "currency_code",
                    models.CharField(blank=True, default="", max_length=3),
                ),
                ("logo_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "primary_color",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                ("manager_id", models.UUIDField(blank=True, null=True)),
                (
                    "is_main_branch",
                    models.BooleanField(
                        default=False,
                        help_text="Only one main branch allowed per organization.",
                    ),
                ),
                (
                    "cascade_deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True when this BU was soft-deleted via parent Organization cascade. Allows selective restore when the parent org is restored.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="business_units",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "db_table": "business_units",
                "ordering": ["name"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserBusinessUnitModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("is_active_membership", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "effective_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Assignment active from this date/time",
                        null=True,
                    ),
                ),
                (
                    "effective_to",
                    models.DateTimeField(
                        blank=True,
                        help_text="Assignment active until this date/time",
                        null=True,
                    ),
                ),
                (
                    "business_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships_new",
                        to="organization.businessunit",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="iam.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bu_memberships_new",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ubu_memberships",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "is_active_membership"],
                        name="ubu_user_active_idx",
                    ),
                    models.Index(
                        fields=["business_unit", "is_active_membership"],
                        name="ubu_bu_active_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="userbusinessunitmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "business_unit", "role"),
                name="unique_active_user_business_unit_role",
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="org_name_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["slug"], name="org_slug_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active", "is_deleted"], name="org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessunitmodule",
            index=models.Index(
                fields=["status", "business_unit_id"],
                name="business_un_status_7af03a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="businessunitmodule",
            index=models.Index(
                fields=["module", "status"], name="business_un_module__a2e479_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="businessunitmodule",
            constraint=models.UniqueConstraint(
                fields=("business_unit_id", "module"),
                name="unique_business_unit_module",
            ),
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(
                fields=["organization", "is_active"], name="bu_org_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(fields=["organization", "code"], name="bu_org_code_idx"),
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(fields=["is_deleted"], name="bu_is_deleted_idx"),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "code"),
                name="unique_bu_code_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False), ("is_main_branch", True)),
                fields=("organization",),
                name="unique_main_branch_per_organization",
            ),
        ),
    ]
