# Generated by Django 4.2.13 on 2026-07-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="business_domain",
            field=models.ForeignKey(
                help_text="The industry classification of the customer.",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="organization_set",
                to="organization.businessdomain",
            ),
        ),
    ]
