# Generated by Django 4.2.13 on 2026-07-05 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_alter_organization_business_domain_related_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessdomain",
            name="slug",
        ),
    ]
