# Generated by Django 4.2.13 on 2026-07-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_org_remove_slug_add_restored_fields_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationsettings",
            name="theme_color",
        ),
    ]
