# Generated by Django 4.2.13 on 2026-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0006_businessdomain_created_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="restored_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
