# Generated by Django 4.2.13 on 2026-07-05 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0007_organization_restored_reason"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="businessunitmodule",
            new_name="bum_status_bu_idx",
            old_name="business_un_status_7af03a_idx",
        ),
        migrations.RenameIndex(
            model_name="businessunitmodule",
            new_name="bum_module_status_idx",
            old_name="business_un_module__a2e479_idx",
        ),
        migrations.AddField(
            model_name="businessunitmodule",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="created_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="deleted_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organizationsettings",
            name="updated_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="businessunitmodule",
            name="id",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AddIndex(
            model_name="businessdomain",
            index=models.Index(
                fields=["is_deleted", "is_active"], name="bd_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="businessdomain",
            index=models.Index(fields=["code"], name="bd_code_idx"),
        ),
    ]
