# Generated by Django 4.2.13 on 2026-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organization",
            "0008_rename_business_un_status_7af03a_idx_bum_status_bu_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="businessunit",
            name="restored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="restored_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessunit",
            name="restored_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="businessunit",
            index=models.Index(fields=["is_main_branch"], name="bu_main_branch_idx"),
        ),
        migrations.AddIndex(
            model_name="userbusinessunitmodel",
            index=models.Index(fields=["user"], name="ubu_user_id_idx"),
        ),
        migrations.AddConstraint(
            model_name="businessunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("organization", "name"),
                name="unique_bu_name_per_org",
            ),
        ),
    ]
