# Generated by Django 4.2.13 on 2026-07-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_enterprise_audit_fixes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessunit",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="organizationsettings",
            name="favicon_url",
        ),
    ]
