# Generated by Django 4.2.13 on 2026-07-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_remove_businessunit_primary_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessdomain",
            name="code",
            field=models.CharField(help_text="e.g. BDOM-RTL", max_length=20),
        ),
        migrations.AlterField(
            model_name="businessdomain",
            name="name",
            field=models.CharField(
                help_text="e.g. Retail, Pharmacy, HRMS", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name="businessdomain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_active_business_domain_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="businessdomain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("code",),
                name="unique_active_business_domain_code",
            ),
        ),
        migrations.AddConstraint(
            model_name="organization",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("name",),
                name="unique_active_organization_name",
            ),
        ),
    ]
