# Generated by Django 4.2.13 on 2026-07-08 00:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NonConformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Denormalized from BU for fast tenant-isolation filtering.",
                    ),
                ),
                (
                    "nc_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="System-assigned NC number on Submit (e.g. NC-2025-L-00001). Blank while Draft.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Under Review", "Under Review"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Assigned", "Assigned"),
                            ("In Progress", "In Progress"),
                            ("Rectified", "Rectified"),
                            ("Verification Pending", "Verification Pending"),
                            ("Approved for Closure", "Approved for Closure"),
                            ("Rework", "Rework"),
                            ("Closed", "Closed"),
                            ("Reopened", "Reopened"),
                            ("Merged", "Merged"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Major", "Major"),
                            ("Minor", "Minor"),
                            ("Observation", "Observation"),
                        ],
                        default="Minor",
                        max_length=20,
                    ),
                ),
                (
                    "is_safety_critical",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Safety-critical NCs override SLA to 24h and trigger immediate escalation.",
                    ),
                ),
                (
                    "location_description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "grid_reference",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "drawing_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "checklist_reference_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text checklist reference for legacy/offline data.",
                        max_length=255,
                    ),
                ),
                (
                    "specification_clause",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "raised_by_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the user who raised this NC."
                    ),
                ),
                (
                    "assigned_to_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="UUID of the engineer assigned to rectify.",
                        null=True,
                    ),
                ),
                (
                    "site_incharge_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the Site Incharge for escalation.",
                        null=True,
                    ),
                ),
                (
                    "site_quality_incharge_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the Site Quality Incharge for escalation.",
                        null=True,
                    ),
                ),
                (
                    "project_incharge_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the Project Incharge for escalation.",
                        null=True,
                    ),
                ),
                (
                    "raised_date",
                    models.DateField(
                        auto_now_add=True, help_text="Date the NC was raised. Auto-set."
                    ),
                ),
                (
                    "target_closure_date",
                    models.DateField(
                        blank=True,
                        help_text="SLA-based target date for NC closure.",
                        null=True,
                    ),
                ),
                (
                    "original_target_closure_date",
                    models.DateField(
                        blank=True,
                        help_text="Preserved original target date for audit trail when extensions granted.",
                        null=True,
                    ),
                ),
                (
                    "actual_closure_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual date the NC was closed.",
                        null=True,
                    ),
                ),
                (
                    "client_captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Offline-sync: timestamp when NC was captured on device.",
                        null=True,
                    ),
                ),
                ("root_cause_description", models.TextField(blank=True, default="")),
                (
                    "root_cause_category",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("corrective_action", models.TextField(blank=True, default="")),
                ("preventive_action", models.TextField(blank=True, default="")),
                (
                    "current_approval_level",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Current verification level reached (0 = not started).",
                    ),
                ),
                (
                    "approval_levels_required",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Total verification levels required before closure.",
                    ),
                ),
                (
                    "reopen_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of times this NC has been reopened.",
                    ),
                ),
                (
                    "backcharge_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Backcharge amount billed to contractor. Visible only to authorized roles.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "backcharge_status",
                    models.CharField(
                        choices=[
                            ("Not Applicable", "Not Applicable"),
                            ("Proposed", "Proposed"),
                            ("Contractor Disputed", "Contractor Disputed"),
                            ("Agreed", "Agreed"),
                            ("Deducted", "Deducted"),
                        ],
                        default="Not Applicable",
                        max_length=30,
                    ),
                ),
                (
                    "is_migrated",
                    models.BooleanField(
                        default=False,
                        help_text="True if imported from legacy Excel/system.",
                    ),
                ),
                (
                    "legacy_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Original reference from legacy system.",
                        max_length=100,
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[("LIVE", "Live"), ("LEGACY", "Legacy (Migrated)")],
                        default="LIVE",
                        help_text="LIVE for production NCs, LEGACY for imported records.",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "db_table": "pqm_non_conformance",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMApprovalStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Denormalized from BU for tenant isolation."
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("review", "Review"),
                            ("verification", "Verification"),
                        ],
                        help_text="Review or Verification stage.",
                        max_length=20,
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveSmallIntegerField(
                        help_text="Order within stage: 1=first approver, 2=second, etc."
                    ),
                ),
                (
                    "approver_id",
                    models.UUIDField(help_text="UUID of the approver for this step."),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Rework", "Rework"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of decision. Null while PENDING.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pqm_approval_step",
                "ordering": ["nc", "stage", "sequence_order"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Denormalized from BU for tenant isolation."
                    ),
                ),
                (
                    "uploaded_by_id",
                    models.UUIDField(
                        help_text="UUID of the user who uploaded this file."
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_key",
                    models.CharField(
                        help_text="S3 object key or storage path. Write-only — never exposed in API responses.",
                        max_length=1000,
                    ),
                ),
                (
                    "file_url",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Temporary signed URL. NOT stored permanently — generated on demand.",
                    ),
                ),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(max_length=100)),
                (
                    "attachment_stage",
                    models.CharField(
                        choices=[
                            ("before", "Before (Evidence)"),
                            ("after", "After (Rectification)"),
                            ("document", "Supporting Document"),
                            ("drawing", "Drawing Reference"),
                            ("report", "Report"),
                        ],
                        help_text="Stage this attachment belongs to (before, after, document, drawing, report).",
                        max_length=20,
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Version counter. Incremented on re-upload of same logical attachment.",
                    ),
                ),
                (
                    "photo_gps_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS latitude from photo EXIF data.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "photo_gps_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        help_text="GPS longitude from photo EXIF data.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "photo_captured_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp from photo EXIF data.",
                        null=True,
                    ),
                ),
                (
                    "photo_exif_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hash of file bytes for deduplication.",
                        max_length=64,
                    ),
                ),
                (
                    "gps_within_geofence",
                    models.BooleanField(
                        blank=True,
                        help_text="True/False/None. Set by geofence_service. Never blocks submission.",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "db_table": "pqm_attachment",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Scoped to organization (shared across BUs)."
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Sort order within same parent level."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pqm_category",
                "ordering": ["display_order", "name"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMChecklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("organization_id", models.UUIDField(help_text="Organization scope.")),
                ("name", models.CharField(max_length=255)),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Checklist version number. Increment on significant revision.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pqm_checklist",
                "ordering": ["name", "-version"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Organization scope — must match parent checklist."
                    ),
                ),
                (
                    "sequence_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display/evaluation order within checklist.",
                    ),
                ),
                (
                    "item_text",
                    models.TextField(
                        help_text="The inspection criterion or check to perform."
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="If True, this item must be addressed before closure.",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_checklist_item",
                "ordering": ["checklist", "sequence_order"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Denormalized from BU for tenant isolation."
                    ),
                ),
                (
                    "author_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the user who wrote this comment.",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "is_internal",
                    models.BooleanField(
                        default=True,
                        help_text="True = staff-only. False = visible to External Client Auditor when project allows.",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_comment",
                "ordering": ["nc", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMContractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Organization scope — shared across BUs within org."
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pqm_contractor",
                "ordering": ["name"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMEscalationConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True, help_text="Organization scope for this config."
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        help_text="NC priority this config applies to.",
                        max_length=20,
                    ),
                ),
                (
                    "sla_days",
                    models.PositiveSmallIntegerField(
                        help_text="Base SLA in business days for this priority."
                    ),
                ),
                (
                    "escalation_day_1",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after target_closure_date to trigger Tier-1 escalation.",
                        null=True,
                    ),
                ),
                (
                    "escalation_1_recipient_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role name for Tier-1 escalation recipients.",
                        max_length=100,
                    ),
                ),
                (
                    "escalation_day_2",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after target_closure_date to trigger Tier-2 escalation.",
                        null=True,
                    ),
                ),
                (
                    "escalation_2_recipient_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role name for Tier-2 escalation recipients.",
                        max_length=100,
                    ),
                ),
                (
                    "escalation_day_3",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days after target_closure_date to trigger Tier-3 escalation.",
                        null=True,
                    ),
                ),
                (
                    "escalation_3_recipient_role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Role name for Tier-3 escalation recipients.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "db_table": "pqm_escalation_config",
                "ordering": ["priority"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMExtensionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Denormalized from BU for tenant isolation."
                    ),
                ),
                (
                    "requested_by_id",
                    models.UUIDField(
                        help_text="UUID of the user requesting the extension."
                    ),
                ),
                (
                    "original_target_date",
                    models.DateField(
                        help_text="NC's target_closure_date at time of this request."
                    ),
                ),
                (
                    "requested_date",
                    models.DateField(help_text="New proposed target_closure_date."),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Justification for the extension request."
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Rework", "Rework"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "decided_by_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the approver who decided on this request.",
                        null=True,
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of decision.", null=True
                    ),
                ),
                (
                    "decision_comments",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional comments from the approver.",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_extension_request",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMNotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Denormalized from BU for tenant isolation.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event that triggered this notification (e.g. nc_submitted, nc_overdue).",
                        max_length=100,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("in_app", "In-App")],
                        help_text="Delivery channel: IN_APP, EMAIL, SMS, PUSH, WEBHOOK.",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_id",
                    models.UUIDField(
                        db_index=True, help_text="UUID of the recipient user."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="queued",
                        help_text="Delivery status: queued / sent / failed.",
                        max_length=20,
                    ),
                ),
                (
                    "error_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Error message if delivery failed.",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of successful delivery.",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "pqm_notification_log",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Denormalized from BU for fast tenant-isolation filtering.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("description", models.TextField(blank=True, default="")),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pqm_project",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMSite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Denormalized from BU for fast tenant-isolation filtering.",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, default="", max_length=30)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("address", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="pqm.pqmproject",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_site",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="Denormalized from BU for tenant isolation.",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        help_text="Event type: StatusChanged, Reassigned, ExtensionGranted, Merged, Reopened, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Previous NC status (empty for non-status events).",
                        max_length=30,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="New NC status (empty for non-status events).",
                        max_length=30,
                    ),
                ),
                (
                    "actor_id",
                    models.UUIDField(
                        help_text="UUID of the user who caused this event."
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Human-readable reason or note for this event.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured extra context for this event (e.g., merged_into NC id).",
                    ),
                ),
                (
                    "nc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="status_history",
                        to="pqm.nonconformance",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_status_history",
                "ordering": ["nc", "created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMSiteGeofence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Denormalized from BU for tenant isolation."
                    ),
                ),
                (
                    "center_lat",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Latitude of geofence center.",
                        max_digits=10,
                    ),
                ),
                (
                    "center_lng",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude of geofence center.",
                        max_digits=10,
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=500, help_text="Radius of geofence circle in meters."
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="geofence",
                        to="pqm.pqmsite",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_site_geofence",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PQMSequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        db_index=True, help_text="Organization scope for the sequence."
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        help_text="Calendar year for this counter (resets annually)."
                    ),
                ),
                (
                    "series",
                    models.CharField(
                        choices=[("LIVE", "Live"), ("LEGACY", "Legacy (Migrated)")],
                        help_text="LIVE or LEGACY series.",
                        max_length=10,
                    ),
                ),
                (
                    "last_value",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Highest sequence number issued. Incremented atomically.",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_sequence_counter",
                "unique_together": {("organization_id", "year", "series")},
            },
        ),
        migrations.CreateModel(
            name="PQMSavedView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        help_text="Organization scope for this saved view."
                    ),
                ),
                (
                    "owner_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the user who created/owns this view.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this saved view.", max_length=100
                    ),
                ),
                (
                    "filter_json",
                    models.JSONField(
                        default=dict,
                        help_text="Serialized filter state for the NC list view.",
                    ),
                ),
                (
                    "is_shared_with_role_id",
                    models.UUIDField(
                        blank=True,
                        help_text="If set, users with this role UUID can access this view.",
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this view loads automatically for the owner.",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_saved_view",
                "ordering": ["name"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("owner_id", "name")},
            },
        ),
        migrations.AddIndex(
            model_name="pqmproject",
            index=models.Index(
                fields=["organization_id", "business_unit_id"],
                name="pqm_project_organiz_62ca66_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmproject",
            unique_together={("business_unit_id", "code")},
        ),
        migrations.AddField(
            model_name="pqmnotificationlog",
            name="nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notification_logs",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="pqmextensionrequest",
            name="nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="extension_requests",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmescalationconfig",
            unique_together={("organization_id", "business_unit_id", "priority")},
        ),
        migrations.AlterUniqueTogether(
            name="pqmcontractor",
            unique_together={("organization_id", "name")},
        ),
        migrations.AddField(
            model_name="pqmcomment",
            name="nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="pqmcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for threading. Null = top-level comment.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="replies",
                to="pqm.pqmcomment",
            ),
        ),
        migrations.AddField(
            model_name="pqmchecklistitem",
            name="checklist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="pqm.pqmchecklist",
            ),
        ),
        migrations.AddField(
            model_name="pqmchecklist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category link for this checklist.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklists",
                to="pqm.pqmcategory",
            ),
        ),
        migrations.AddField(
            model_name="pqmcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent category. Null = top-level category.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="pqm.pqmcategory",
            ),
        ),
        migrations.AddField(
            model_name="pqmattachment",
            name="nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attachments",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="pqmapprovalstep",
            name="nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approval_steps",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_conformances",
                to="pqm.pqmcategory",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="checklist_reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured checklist reference (preferred).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_conformances",
                to="pqm.pqmchecklist",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_conformances",
                to="pqm.pqmcontractor",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="linked_nc",
            field=models.ForeignKey(
                blank=True,
                help_text="Links to a recurring-issue family head NC.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_ncs",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="merged_into_nc",
            field=models.ForeignKey(
                blank=True,
                help_text="Target NC this was merged into. Set on MERGED transition.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_ncs",
                to="pqm.nonconformance",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_conformances",
                to="pqm.pqmproject",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="non_conformances",
                to="pqm.pqmsite",
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sub_category_ncs",
                to="pqm.pqmcategory",
            ),
        ),
        migrations.AddIndex(
            model_name="pqmstatushistory",
            index=models.Index(
                fields=["nc_id", "created_at"], name="pqm_status__nc_id_de1f7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pqmsite",
            index=models.Index(
                fields=["organization_id"], name="pqm_site_organiz_d668a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pqmsite",
            index=models.Index(
                fields=["business_unit_id"], name="pqm_site_busines_1a6d2a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmsite",
            unique_together={("project", "code")},
        ),
        migrations.AddIndex(
            model_name="pqmcomment",
            index=models.Index(
                fields=["nc_id", "created_at"], name="pqm_comment_nc_id_c82f7c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmcategory",
            unique_together={("organization_id", "name", "parent")},
        ),
        migrations.AddIndex(
            model_name="pqmattachment",
            index=models.Index(
                fields=["nc_id", "attachment_stage"],
                name="pqm_attachm_nc_id_e6e945_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pqmattachment",
            index=models.Index(
                fields=["nc_id", "version"], name="pqm_attachm_nc_id_d19149_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmapprovalstep",
            unique_together={("nc", "stage", "sequence_order")},
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(
                fields=["organization_id", "status"],
                name="pqm_non_con_organiz_1759a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(
                fields=["business_unit_id", "status"],
                name="pqm_non_con_busines_0ed5f1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(
                fields=["assigned_to_id", "status"],
                name="pqm_non_con_assigne_943074_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(
                fields=["is_safety_critical", "status"],
                name="pqm_non_con_is_safe_a250c4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformance",
            index=models.Index(
                fields=["project_id", "status"], name="pqm_non_con_project_2e18f6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="nonconformance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("target_closure_date__isnull", True),
                    ("target_closure_date__gte", models.F("raised_date")),
                    _connector="OR",
                ),
                name="pqm_nc_target_closure_gte_raised",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonconformance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("actual_closure_date__isnull", True),
                    ("actual_closure_date__gte", models.F("raised_date")),
                    _connector="OR",
                ),
                name="pqm_nc_actual_closure_gte_raised",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonconformance",
            constraint=models.CheckConstraint(
                check=models.Q(("current_approval_level__gte", 0)),
                name="pqm_nc_approval_level_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="nonconformance",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        [
                            "Draft",
                            "Submitted",
                            "Under Review",
                            "Approved",
                            "Rejected",
                            "Assigned",
                            "In Progress",
                            "Rectified",
                            "Verification Pending",
                            "Approved for Closure",
                            "Rework",
                            "Closed",
                            "Reopened",
                            "Merged",
                        ],
                    )
                ),
                name="pqm_nc_valid_status",
            ),
        ),
    ]
