# Generated by Django 4.2.13 on 2026-07-08 13:12

import django.contrib.postgres.indexes
from django.db import migrations, models
import uuid
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('pqm', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='PQMDrawingReference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('created_reason', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_reason', models.TextField(blank=True, default='')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_reason', models.TextField(blank=True, default='')),
                ('business_unit_id', models.UUIDField(db_index=True, help_text='The business unit this record belongs to. NEVER cross-tenant.')),
                ('organization_id', models.UUIDField(db_index=True, help_text='Organization ID')),
                ('project_id', models.UUIDField(db_index=True, help_text='Project ID')),
                ('drawing_number', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=50)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pqm_drawing_reference',
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='nonconformance',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='pqm_nc_title_desc_gin', opclasses=['gin_trgm_ops', 'gin_trgm_ops']),
        ),
    ]
