# Generated by Django 4.2.13 on 2026-07-08 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0002_pqmdrawingreference_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PQMAccessRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                (
                    "projects",
                    models.JSONField(default=list, help_text="List of project UUIDs"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("justification", models.TextField(blank=True, default="")),
                ("approved_by_id", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "pqm_access_request",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
            },
        ),
        migrations.RenameField(
            model_name="pqmproject",
            old_name="end_date",
            new_name="expected_project_end_date",
        ),
        migrations.RenameField(
            model_name="pqmproject",
            old_name="start_date",
            new_name="project_start_date",
        ),
        migrations.AddField(
            model_name="pqmproject",
            name="capacity",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="pqmproject",
            name="construction_incharge_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pqmproject",
            name="project_head_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pqmproject",
            name="quality_head_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pqmproject",
            name="quality_incharge_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PQMProjectMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("user_id", models.UUIDField(db_index=True)),
                ("role", models.CharField(default="MEMBER", max_length=50)),
                ("assigned_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="pqm.pqmproject",
                    ),
                ),
            ],
            options={
                "db_table": "pqm_project_member",
                "ordering": ["-created_at"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("project", "user_id")},
            },
        ),
    ]
