# Generated by Django 4.2.13 on 2026-07-09 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0003_pqmaccessrequest_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pqmsequencecounter",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="nonconformance",
            name="drawing_reference",
        ),
        migrations.RemoveField(
            model_name="nonconformance",
            name="grid_reference",
        ),
        migrations.RemoveField(
            model_name="nonconformance",
            name="site",
        ),
        migrations.RemoveField(
            model_name="nonconformance",
            name="specification_clause",
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="reference_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Details of the reference.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="reference_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Drawing", "Drawing"),
                    ("Document", "Document"),
                    ("Specification", "Specification"),
                    ("Other", "Other"),
                ],
                default="",
                help_text="Type of reference document or drawing.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="pqmsequencecounter",
            name="project_id",
            field=models.UUIDField(
                db_index=True,
                default="00000000-0000-0000-0000-000000000000",
                help_text="Project scope for the sequence.",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="raised_date",
            field=models.DateField(
                default=django.utils.timezone.now, help_text="Date the NC was raised."
            ),
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="severity",
            field=models.CharField(
                choices=[("Major", "Major"), ("Minor", "Minor")],
                default="Minor",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pqmsequencecounter",
            unique_together={("organization_id", "project_id", "year", "series")},
        ),
    ]
