# Generated by Django 4.2.13 on 2026-07-09 18:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0004_alter_pqmsequencecounter_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PQMDropdownOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_by_id", models.UUIDField(blank=True, null=True)),
                ("created_reason", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by_id", models.UUIDField(blank=True, null=True)),
                ("updated_reason", models.TextField(blank=True, default="")),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_by_id", models.UUIDField(blank=True, null=True)),
                ("deleted_reason", models.TextField(blank=True, default="")),
                (
                    "business_unit_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The business unit this record belongs to. NEVER cross-tenant.",
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("PRIORITY", "Priority"),
                            ("SEVERITY", "Severity"),
                            ("REFERENCE_TYPE", "Reference Type"),
                            ("AREA", "Area of NC Raised"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "system_mapping",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Used to map custom options to system logic (e.g. mapping to 'Critical' for dashboard KPIs)",
                        max_length=50,
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "pqm_dropdown_option",
                "ordering": ["field_type", "display_order", "name"],
                "get_latest_by": "created_at",
                "abstract": False,
                "unique_together": {("organization_id", "field_type", "name")},
            },
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="location_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_areas",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_priorities",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="reference_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_reference_types",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="severity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_severities",
                to="pqm.pqmdropdownoption",
            ),
        ),
    ]
