# Generated by Django 4.2.13 on 2026-07-10 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0005_pqmdropdownoption_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonconformance",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_categories",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="nonconformance",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nc_sub_categories",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="pqmchecklist",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional category link for this checklist.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checklists",
                to="pqm.pqmdropdownoption",
            ),
        ),
        migrations.AlterField(
            model_name="pqmdropdownoption",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("PRIORITY", "Priority"),
                    ("SEVERITY", "Severity"),
                    ("REFERENCE_TYPE", "Reference Type"),
                    ("AREA", "Area of NC Raised"),
                    ("CATEGORY", "Category"),
                    ("SUB_CATEGORY", "Sub-category"),
                ],
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="PQMCategory",
        ),
    ]
