# Generated by Django 4.2.13 on 2026-07-10 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0006_alter_nonconformance_category_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pqmcontractor",
            unique_together={("business_unit_id", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="pqmdropdownoption",
            unique_together={("business_unit_id", "field_type", "name")},
        ),
    ]
