# Generated by Django 4.2.13 on 2026-07-10 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0007_alter_pqmcontractor_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pqmcontractor",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contractors",
                to="pqm.pqmproject",
            ),
        ),
    ]
