# Generated by Django 4.2.13 on 2026-07-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0008_pqmcontractor_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformance",
            name="block",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Block D", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="drawing_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="GA drawing / SLD number",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="location_details",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specific location, e.g. Block D, Row 14",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="specification_reference",
            field=models.CharField(
                blank=True, default="", help_text="e.g. DBR-2024-Rev2", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="standard_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. IEC 62446-1, MNRE guideline ref",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="work_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="e.g. MMS erection, DC string termination, blade installation",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="nonconformance",
            name="zone",
            field=models.CharField(
                blank=True, default="", help_text="e.g. Zone C", max_length=100
            ),
        ),
    ]
