# Generated by Django 4.2.13 on 2026-07-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pqm", "0009_nonconformance_block_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nonconformance",
            name="work_type",
        ),
    ]
