# Generated by Django 4.2.13 on 2026-07-05 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("exception_type", models.CharField(blank=True, max_length=255)),
                ("traceback", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("ERROR", "Error"),
                            ("WARNING", "Warning"),
                            ("INFO", "Info"),
                        ],
                        default="ERROR",
                        max_length=20,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "business_unit_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "error_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["severity", "resolved", "created_at"],
                        name="error_logs_severit_bd8093_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="error_logs_correla_05a210_idx"
                    ),
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="error_logs_user_id_71f3b9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("user_username", models.CharField(blank=True, max_length=150)),
                ("is_impersonated", models.BooleanField(default=False)),
                ("impersonated_by_id", models.UUIDField(blank=True, null=True)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "business_unit_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Created"),
                            ("UPDATE", "Updated"),
                            ("DELETE", "Deleted"),
                            ("LOGIN", "Logged In"),
                            ("LOGOUT", "Logged Out"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("MFA_ENABLED", "MFA Enabled"),
                            ("MFA_DISABLED", "MFA Disabled"),
                            ("PERMISSION_GRANTED", "Permission Granted"),
                            ("PERMISSION_REVOKED", "Permission Revoked"),
                            ("ROLE_ASSIGNED", "Role Assigned"),
                            ("IMPERSONATION_STARTED", "Impersonation Started"),
                            ("IMPERSONATION_ENDED", "Impersonation Ended"),
                            ("DATA_EXPORTED", "Data Exported"),
                            ("SUBSCRIPTION_CHANGED", "Subscription Changed"),
                            ("MODULE_ACTIVATED", "Module Activated"),
                            ("MODULE_DEACTIVATED", "Module Deactivated"),
                            ("STOCK_ADJUSTED", "Stock Adjusted"),
                            ("PAYROLL_RUN", "Payroll Run"),
                            ("PAYMENT_PROCESSED", "Payment Processed"),
                            ("CUSTOM", "Custom Event"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(db_index=True, default="UNKNOWN", max_length=100),
                ),
                ("resource_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("resource_display", models.CharField(blank=True, max_length=255)),
                ("old_values", models.JSONField(blank=True, null=True)),
                ("new_values", models.JSONField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("request_id", models.CharField(blank=True, max_length=36)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=255)),
                ("http_method", models.CharField(blank=True, max_length=10)),
                ("extra", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("chain_hash", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business_unit_id", "created_at"],
                        name="audit_logs_busines_5ef09a_idx",
                    ),
                    models.Index(
                        fields=["user_id", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_logs_resourc_bda8a6_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="audit_logs_correla_953e51_idx"
                    ),
                ],
            },
        ),
    ]
